name: Auto-bump-version on merging a Pull Request

on:
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:
    branches:
      - master

jobs:
  Create Tag:
    runs-on: ubuntu-latest
#    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
