name: Create Tag

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'             # Все файлы в каталоге src и его подкаталогах
      - 'config/**'          # Если у вас есть каталог с конфигурационными файлами
      - 'public/**'          # Если у вас есть каталог с публичными ресурсами (например, для фронтенда)
      - 'package.json'       # Для отслеживания изменений в зависимостях
      - 'package-lock.json'  # Для точного отслеживания версий зависимостей
      - '.env*'               # Если у вас есть файл с переменными окружения
      - '.eslintrc'          # Если вы используете ESLint для линтинга вашего кода
      - 'tsconfig.json'      # Если вы используете TypeScript
      - '**/*.ts'            # Все TypeScript файлы
      - '**/*.js'            # Все JavaScript файлы
jobs:
  update-deps:
    name: Bump Node version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: neverendingqs/gh-action-node-bump-version-pr@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type:
            default: patch
            description: Bumps the package version based on value (e.g. patch)
            required: true


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
          changelog_structure: "**{{messageHeadline}}** {{author}}\n"
          version: "${{ steps.previous_step.outputs.version }}"
